### ISSUE TITLE
News Website Scrapping Project Review

### ISSUE THREAD

**Issue by ceciliawambui** [WNderitu/Webscrap_project#1]
### What I like about your project

1. The basic structure of how web scrapping is done is great.
2. The code is simple, clear and easy to understand.

### Areas of improvements

1. Make use of comments to improve readability.
2. Your code is scrapping all h2 and p tags even if they don't contain the headlines and summaries of the news. eg. It scraps the footer which is a p tag, but it's not a news summary. Make use of classes for the specific h2 and p tags that contain the data you need.
3. You can incorporate error handling for HTTP Requests i.e response.status_code == 200 to check for any request errors.

**Comment by WNderitu** [comment]
I've made edits after your recommendations on areas of improvement. Kindly check.

**Comment by ceciliawambui** [comment]
The project is now all good.
